### ISSUE TITLE
hello webapp

### ISSUE THREAD

**Issue by muly** [pk80/golang#1]
acceptance criteria: 
- [x] develop a simple hello world web app using go and run it locally.

useful web reference: TODO: need to add the blog here

**Comment by muly** [comment]
useful web reference: TODO: need to add the blog here

**Comment by pk80** [comment]
Completed task developing simple hello world web app using go and able to run it successfully.
http://localhost:63342/src/src/github.com/pk80/golang/helloworld.html?_ijt=ndduitlkqa52jivrmhienq2o8i
