### ISSUE TITLE
REST API basics

### ISSUE THREAD

**Issue by muly** [pk80/golang#5]
Methods
- [x] GET
- [x] POST
- [x] DELETE
- [x] PUT

and
- [x] URI structure
And more

**Comment by pk80** [comment]
**## HTTP methods:**
- [ ] GET retrieves the data from the resource and is idempotent & read only method.
- [ ] POST submits the data to the resource and is non-idempotent & write method.
- [ ] DELETE deletes the data from the resource and is idempotent & write method.
- [ ] PUT updates the data to the resource and is idempotent & write method.
- [ ] HEAD like GET it gets the header part in the resource
- [ ] OPTIONS returns the supported HTTP methods
- [ ] PATCH update partial resource

**##URI Structure:**
- [ ] Protocol  : https:// or http:// ( followed by REST API endpoint URL)
- [ ] Host        : database or homepage (API method includes key/token)
- [ ] Resource : path (Parameters include secret code)

**Comment by pk80** [comment]
Very interesting
