### ISSUE TITLE
JSON basics

### ISSUE THREAD

**Issue by muly** [pk80/golang#6]

**Comment by pk80** [comment]
**# JSON basics covered:**
- Intro
- Uses & Characteristics
- Syntax
- Use in go
- Data types
- Objects & Arrays
- Validation of JSON code : jsonlint.com
- Parsing
- JSON vs XML
- JSON Schema:(keys-type,required,properties,format,pattern,etc...)
- JSON formats:(date-time,email,hostname,uri, etc..)
- JSON types:(number,string,object,array,boolean,null)

**Comment by pk80** [comment]
Need an example on json.parse() or is it json.evel().
